import {build} from 'esbuild';
import fs from 'node:fs/promises';
import postcss from 'postcss';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import config from '../tailwind.config.cjs';
await fs.mkdir('dist',{recursive:true});
await build({entryPoints:['src/main.tsx'],outfile:'dist/app.js',bundle:true,minify:true,platform:'browser',format:'esm',target:['es2022'],loader:{'.css':'empty'},define:{'process.env.NODE_ENV':'"production"'}});
const css=await postcss([tailwindcss(config),autoprefixer]).process(await fs.readFile('src/styles.css','utf8'),{from:'src/styles.css',to:'dist/app.css'});
await fs.writeFile('dist/app.css',css.css);
await fs.writeFile('dist/index.html','<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Omni500 Agent Workspace</title><link rel="stylesheet" href="/app.css"></head><body><div id="root"></div><script type="module" src="/app.js"></script></body></html>');
console.log('Built dist/index.html, app.js and app.css');
